### ISSUE TITLE
Upload debian package for 0.1.1

### ISSUE THREAD

**Issue by radicand** [TriJetScud/vyos-agile-vpn#2]
I noticed the is a GitHub release that adds the necessary OSX/iOS server id key, but no debian release. Could you upload the `.deb` to the release, and/or provide the recommend build instructions to generate it from source?

**Comment by TriJetScud** [comment]
Currently the way to build the packages is to install a Debian 6 or 7 environment with the appropriate tools to build packages.

After that, go into the root directory of the source and run:

dpkg-buildpackage -uc -us
